name: "Ad Group Creation Request"
description: "Submit details to create a new Active Directory group"
title: "[Ad Group] <Enter group name here>"
labels: ["ad-group-request"]
body:
  - type: input
    id: group_name
    attributes:
      label: "Group Name"
      description: "Enter the AD group name to be created"
      placeholder: "e.g., DevOps-Team"
    validations:
      required: true

  - type: textarea
    id: user_details
    attributes:
      label: "User Details"
      description: "Provide user details to be added (e.g., Name, Email, Username)"
      placeholder: |
        - Name: John Doe
          Email: john.doe@example.com
          Username: jdoe
        - Name: Jane Smith
          Email: jane.smith@example.com
          Username: jsmith
    validations:
      required: true

  - type: dropdown
    id: enable_group
    attributes:
      label: "Enable Group Immediately?"
      description: "Choose whether this group should be enabled after creation"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
