AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 Bucket

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: mybucjet10215
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

Outputs:
  S3BucketName:
    Value: !Ref MyS3Bucket
    Description: The name of the S3 bucket
